defaults: &defaults
  working_directory: ~/dashbase-cloudformation-template
  machine:
    enabled: true
  

version: 2
jobs:
  deploy-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Copy to S3 CloudFormation Test
          command: aws s3 sync --exclude="*" --include="dashbase-cf-*" . s3://dashbase-public/cloudformation-template/test/
  deploy-master:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Copy to S3 CloudFormation
          command: aws s3 sync --exclude="*" --include="dashbase-cf-*" . s3://dashbase-public/cloudformation-template/

workflows:
  version: 2
  build:
    jobs:
      - deploy-test:
          filters:
            branches:
              ignore: master
      - deploy-master:
          filters:
            branches:
              only:
                - master